server.port=8081

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/fraud
spring.datasource.username=fraud
spring.datasource.password=fraud

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
