server.port=8081

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/hh
spring.datasource.username=hh
spring.datasource.password=hh

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
